neon-focal:
  image: kdeneon/plasma:unstable
  before_script:
   - ./ci_scripts/debian-install-deps.sh
  script:
   - ./ci_scripts/build.sh

debian-sid:
  image: debian:unstable
  before_script:
   - ./ci_scripts/debian-install-deps.sh
  script:
   - ./ci_scripts/build.sh

fedora-33:
  image: fedora:33
  before_script:
   - ./ci_scripts/fedora-install-deps.sh
  script:
   - ./ci_scripts/build.sh

cache:
  paths:
    - ccache/
